[package]
name = "rusts3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
aws-config = "0.48.0"
aws-sdk-s3 = "0.18.0"
tokio = { version = "1", features = ["full"] }
